#!/bin/bash -e

STDIN=$(< /dev/stdin)

printf -v PROMPT '$ %s\nAllow execution? (Y/n) ' "$STDIN"
{ flock 0 && read -p "$PROMPT" -r REPLY; } <>/dev/tty >&0 2>&0

if [[ $? -eq 0 ]] && [[ $REPLY == ?([Yy]*) ]]; then
  SHELL=$(type -P bash) exec bash <<< "$STDIN"
else
  echo 'User denied permission to execute this command' >&2
  exit 1
fi
