#!/bin/bash

export -n $(compgen -e)
export API HOME KEY LOG LOGNAME MODEL REASONING TOOLS USER
export PATH=/bin SHELL=/bin/bash

if set -e -o noclobber; 2>/dev/null >/run/ua.ns; then
  unshare --user=/run/ua.ns --map-{users,groups}=0:65536:65535 true
fi

if LOG=$(realpath "$LOG") && [[ $LOG == "$PWD"/* ]]; then
  LOG=~/${LOG#"$PWD"/}
elif [[ -z $LOG ]] || [[ $LOG == ~/* ]]; then
  unset LOG
fi 2>/dev/null

exec setsid -w unshare -m sh -e /dev/fd/3 3<<EOF
  mount -m -n --bind --map-users=/run/ua.ns . ~
  cd && exec nsenter -S 0 -G 0 --user=/run/ua.ns bash 3>&-
EOF
